#!/usr/bin/perl
# Copyright (C) 2021 The uecho-py Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if (@ARGV < 1){
  exit 1;
}
my $devlist_filename = $ARGV[0];

print<<HEADER;
# Copyright (C) 2021 The uecho-py Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To the extent possible under law, Sony Computer Science Laboratories, Inc has waived 
# all copyright and related or neighboring rights to ECHONETLite-ObjectDatabase. 
# This work is published from: Japan.
#
# GENERATED FROM objects.pl DO NOT EDIT THIS FILE.

from .object import Object
from .property import Property
from .objects_appendix import get_all_std_appendix_objects

__std_objects: dict = {}


def get_all_std_objects() -> dict:
    all_std_objects = {}
    all_std_objects.update(__std_objects)
    all_std_objects.update(get_all_std_appendix_objects())
    return all_std_objects

HEADER

open(DEVLIST, $devlist_filename) or die "$!";
my $devlist_row_no = 0;
while(<DEVLIST>){
  $devlist_row_no++;
  if ($devlist_row_no <= 1) {
    next;
  }
  chomp($_);
  $_ =~ s/(['"].*?['"])/(my $s = $1) =~ tr|,| |; $s/eg;
  my @row = split(/(?!"),/, $_, -1);;
  my $cls_name = $row[0];
  my $grp_code = substr($row[2], 2);
  my $cls_code = substr($row[3], 2);
  my $dev_filename = "0x" . $grp_code  . $cls_code . ".csv";
  my $dev_fileurl = "https://raw.githubusercontent.com/SonyCSL/ECHONETLite-ObjectDatabase/master/data/csv/en/" . $dev_filename;
  my $rc = system("wget -q -O " . $dev_filename . " " . $dev_fileurl);
  if ($rc >> 8) {
    next;
  }

  printf("# %s (0x%s%s)\n", $cls_name, $grp_code, $cls_code);
  printf("obj = Object(\"%s\", 0x%s, 0x%s)\n", $cls_name, $grp_code, $cls_code);
  open(DEV, $dev_filename) or die "$!";
  $dev_row_no++;
  while(<DEV>){
    $dev_row_no++;
    if ($dev_row_no <= 1) {
      next;
    }
    chomp($_);
    $_ =~ s/(['"].*?['"])/(my $s = $1) =~ tr|,| |; $s/eg;
    my @row = split(/(?!"),/, $_, -1);;
    my $epc = substr($row[0], 2);
    if (length($epc) != 2) {
      next;
    }
    my $name = $row[1];
    my $data_rng = $row[3];
    my $data_type = $row[5];
    my $data_size = $row[6];
    my $anno_rule = $row[7];
    my $set_rule = $row[8];
    my $get_rule = $row[9];
    my $stat_chg = $row[10];

    $data_rng =~ s/^\"|\"$//g;
    $data_type =~ s/^\"|\"$//g;

    printf("obj.add_property(Property(0x%s, \"%s\", \"%s\", %d, \"%s\", \"%s\", \"%s\", \"%s\"))\n",
      $epc,
      $name,
      $data_type,
      $data_size,
      $get_rule,
      $set_rule,
      $anno_rule,
      $stat_chg,
      );
  }
  close(DEV);
  printf("__std_objects[(0x%s, 0x%s)] = obj\n\n", $grp_code, $cls_code);
}
close(DEVLIST);
print<<FOTTER;
FOTTER