name: "doc"

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/conf"
        pre-build-command: "pip install sphinx-rtd-theme"
        build-command: "sphinx-build -b singlehtml . _build"
    - name: Commit documentation changes
      run: |
        git clone https://github.com/cybergarage/uecho-py.git --branch gh-pages --single-branch gh-pages
        mkdir -p gh-pages/docs
        cp -r doc/conf/_build/* gh-pages/docs/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub"
        git add docs
        touch docs/.nojekyll
        git add docs/.nojekyll
        git commit -m "Update documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
